# Generated by Django 4.2.27 on 2025-12-30 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='longtitude')),
                ('address', models.TextField()),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
