# Generated by Django 4.2.27 on 2025-12-31 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='hero_image'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='event_image'),
        ),
    ]
