# Generated by Django 4.2.27 on 2025-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_image_alter_event_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embeded_map',
            field=models.TextField(default='Please insert HTML for an embeded google map'),
        ),
    ]
