# Generated by Django 4.2.27 on 2025-12-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_embeded_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
