# Generated by Django 4.2.27 on 2025-12-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated_at']},
        ),
    ]
