# Generated by Django 4.2.27 on 2025-12-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
