# Generated by Django 4.2.27 on 2025-12-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_parent_comment_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
