# Generated by Django 4.2.27 on 2026-01-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_parent_id_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
