# Generated by Django 4.2.27 on 2026-01-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
