# Generated by Django 4.2.27 on 2026-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
