# Generated by Django 4.2.27 on 2026-01-02 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='event image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='hero image'),
        ),
    ]
